export const config = {
  photographer: {
    name: "Ina j Photography",
    logoPath: "/logo.png",
    websiteUrl: "https://inajphotography.com",
    ctaLabel: "Back to your session guide",
    ctaUrl: "https://inajphotography.com/session-guide",
  },
  subjects: [
    { noun: "dog", nounPlural: "dogs", coatWord: "coat" },
    { noun: "cat", nounPlural: "cats", coatWord: "fur" },
    { noun: "horse", nounPlural: "horses", coatWord: "coat" },
  ],
  collectiveNoun: "animal",
  locations: [
    { id: "studio", label: "The Studio", kind: "studio",
      description: "Ina's studio in Jerrabomberra. The backdrop is chosen rather than found, so the backdrop is the environment.",
      palette: [] },
    { id: "yarralumla", label: "Yarralumla English Garden", kind: "outdoor",
      description: "Natural, vibrant and serene. A secret woodland garden with winding paths, mature trees and dense foliage. Shot at golden hour, so the frame reads warm.",
      palette: ["#403B10", "#714E22", "#7A623A", "#88754F", "#AA937A"],
      seasonalNotes: {
        spring: "In spring the garden is under a pink blossom canopy, so blush, dusty pink and lilac will disappear into it.",
        autumn: "In autumn it is golden light over a carpet of fallen leaves, so gold, rust, camel and mustard will disappear into it.",
      } },
    { id: "fetherston", label: "Fetherston Gardens", kind: "outdoor",
      description: "Tranquil, intimate and natural. Native and exotic planting, winding paths, a small pond and wooden structures. The greenest of the outdoor locations.",
      palette: ["#524623", "#7C7636", "#27280D", "#AB844E", "#BAA885"] },
    { id: "lindsay-pryor", label: "Lindsay Pryor National Arboretum", kind: "outdoor",
      description: "Natural, rugged and expansive. Mature and rare trees over wide open fields, a canvas of earthy tones and textures.",
      palette: ["#604F34", "#391E15", "#9E7F5D", "#856D58", "#B9AC9E"],
      seasonalNotes: {
        autumn: "Strong autumn colour through the trees, so rust and burnt orange will disappear into it.",
      } },
    { id: "lake-burley-griffin", label: "Lake Burley Griffin", kind: "outdoor",
      description: "Iconic, grand and modern, across the National Gallery and National Library precincts. The only location carrying real blue, off the water and the architectural greys.",
      palette: ["#99B4C9", "#9F9EA6", "#875D57", "#50231C", "#5D4E2F"] },
    { id: "lennox", label: "Lennox Gardens", kind: "outdoor",
      description: "Serene, cultural and picturesque. The Beijing Garden pavilion and the Nara Peace Park. The red pavilion is already a strong pop of colour in frame.",
      palette: ["#7D5D47", "#31251D", "#A28D7C", "#654D3F", "#91754F"] },
    { id: "commonwealth-park", label: "Commonwealth Park", kind: "outdoor",
      description: "Classic, spacious and iconic. Sprawling lawns, ponds and mature trees with lakeside views. Lighter than the gardens, with pale greys and creams off the lawns.",
      palette: ["#5E502F", "#42301E", "#A1846A", "#B5ADA8", "#DDD0BE"] },
    { id: "pialligo-redwoods", label: "Pialligo Redwood Forest", kind: "outdoor",
      description: "Dramatic, structured and awe-inspiring. Hundreds of towering straight redwood trunks with soft filtered light. The darkest location by a distance.",
      palette: ["#3A2B1D", "#5F4734", "#6F614B", "#17120A", "#A88B7D"] },
    { id: "palmerville", label: "Palmerville Heritage Park", kind: "outdoor",
      description: "Natural, open and relaxed, with a countryside feel. Open grassy fields, heritage trees and rustic tracks.",
      palette: ["#6B5445", "#8F7158", "#3D2C1F", "#B9984F", "#DFC3A0"] },
    { id: "national-arboretum", label: "National Arboretum", kind: "outdoor",
      description: "Dairy Farmers Hill and the cedar forests. Panoramic views and a great deal of open sky, so it is the lightest of the outdoor locations.",
      palette: ["#DFBABA", "#DFE8E9", "#D8D6C7", "#7A6455", "#8F7C5D"],
      seasonalNotes: {
        summer: "The sunset sky here reads pink rather than blue, so blush and dusty pink will disappear into it.",
        autumn: "The sunset sky here reads pink rather than blue, so blush and dusty pink will disappear into it.",
        winter: "The sunset sky here reads pink rather than blue, so blush and dusty pink will disappear into it.",
        spring: "The sunset sky here reads pink rather than blue, so blush and dusty pink will disappear into it.",
      } },
  ],
  backdrops: [
    { id: "mauvey-pink", label: "Mauvey pink", family: "muted pink", depth: "mid", approxHex: "#C89AA0" },
    { id: "brown", label: "Brown", family: "warm brown", depth: "deep", approxHex: "#6E5F5C" },
    { id: "cream", label: "Cream", family: "warm neutral", depth: "light", approxHex: "#F0E8DA" },
    { id: "black", label: "Black", family: "neutral", depth: "deep", approxHex: "#1A1A1A" },
    { id: "white", label: "White", family: "neutral", depth: "light", approxHex: "#F7F7F5" },
    { id: "light-blue", label: "Light blue", family: "cool blue", depth: "light", approxHex: "#B9C4C8" },
    { id: "pink", label: "Pink", family: "warm pink", depth: "mid", approxHex: "#DE9A9B" },
    { id: "bright-yellow", label: "Bright yellow", family: "warm yellow", depth: "light", approxHex: "#E8C93E" },
  ],
  voice: {
    australianEnglish: true,
    bannedPhrases: ["quiet", "quietly", "a good amount", "just a touch", "a little of"],
    notes: [
      "No em dashes, ever.",
      "Never describe a colour as quiet.",
      "No constructed aphorisms and no balanced this-versus-that sentences. Say the actual thing, the way a person would say it.",
      "Never name a garment to prescribe an outfit. Garment words are only for scale and placement, because some people wear dresses and some wear trousers.",
      "Instruction first, then one clause of why.",
      "Do not explain the colour theory. Give the instruction.",
    ],
  },
  branding: {
    coralRed: "#CA5E3C",
    darkGreen: "#232817",
    lightGreen: "#99934F",
    ivory: "#EEE8E0",
    ivoryLight: "#F7F4ED",
    lightPink: "#EABDAC",
    lightPinkMuted: "#F3E1D3",
    darkTeal: "#0F6668",
    darkBrown: "#6D341B",
    headingFont: "Alice",
    bodyFont: "Quicksand",
  },
  copy: {
    pageTitle: "What to Wear for Your Session",
    pageSubtitle: "Upload a photo of your animal and we'll create a personalised colour palette for your photography session.",
    uploadGuidelines: [
      "Clear photo of your animal in natural light",
      "One animal only for the most accurate palette",
      "Face and coat clearly visible",
    ],
    privacyNote: "Your photo isn't stored after analysis",
    toneNote: "These are the tones to aim for, not exact matches. Anything close to these works.",
  },
} as const
